services:
  - type: web
    name: ms-login
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node src/app.js
    envVars:
      - key: PORT
        value: 4002

      # Google Sheets
      - key: GOOGLE_SHEET_ID
        sync: false
      - key: GOOGLE_SERVICE_ACCOUNT_EMAIL
        sync: false
      - key: GOOGLE_PRIVATE_KEY
        sync: false

      # Configuración de hojas
      - key: CONF_SHEET_NAME
        value: ConfPlataformas
      - key: SHEETS_NEW
        value: NuevosUsuarios
      - key: CONF_COL_PLATAFORMA
        value: PLATAFORMA
      - key: CONF_COL_URL_LOGIN
        value: URL
      - key: CONF_COL_USER
        value: USUARIO
      - key: CONF_COL_PASS
        value: CONTRASEÑA

      # Cron de keepalive
      - key: KEEPALIVE_CRON
        value: "*/10 * * * *"

      # Puppeteer
      - key: PUPPETEER_HEADLESS
        value: "true"
      - key: PUPPETEER_ARGS
        value: "--no-sandbox,--disable-setuid-sandbox,--ignore-certificate-errors"

      # Timeout
      - key: LOGIN_TIMEOUT_MS
        value: "30000"

      # Bright Data Proxy
      - key: PROXY_PROTOCOL
        value: http
      - key: PROXY_HOST
        value: brd.superproxy.io
      - key: PROXY_PORT
        value: "33335"
      - key: PROXY_USER
        value: brd-customer-hl_68fd24b8-zone-residential_proxy1
      - key: PROXY_PASS
        value: 68hr2c9qdf2v
      

